# Auto-generated by CMake - DO NOT EDIT
# Makefile wrapper for developers (uses CMake underneath)
# Users: Use build.sh instead (no CMake required)

.PHONY: all build test test-c test-lua clean help

all: build

build:
	@cmake -B build -S .
	@cmake --build build
	@echo "✓ Build successful"

test: test-c test-lua

test-c: build
	@cd build && ctest --output-on-failure

test-lua:
	@./tests/run_plenary_tests.sh

clean:
	@rm -rf build
	@rm -f libvscode_diff.so libvscode_diff.dylib

help:
	@echo "Targets: build, test, test-c, test-lua, clean, help"
